apiVersion: apps/v1
kind: Deployment
metadata:
  name: event-backend
  labels:
    app: event-backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: event-backend
  template:
    metadata:
      labels:
        app: event-backend
    spec:
      containers:
        - name: event-backend
          image: mahmoud3331/event-backend:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 8082
          envFrom:
            - secretRef:
                name: event-backend-db
          env:
            - name: SPRING_JPA_HIBERNATE_DDL_AUTO
              value: update
            - name: EUREKA_CLIENT_REGISTER_WITH_EUREKA
              value: "false"
            - name: EUREKA_CLIENT_FETCH_REGISTRY
              value: "false"
          resources:
            requests:
              cpu: "200m"
              memory: "512Mi"
            limits:
              cpu: "1000m"
              memory: "1Gi"
          livenessProbe:
            httpGet:
              path: /actuator/health
              port: 8082
            initialDelaySeconds: 60
            periodSeconds: 30
          readinessProbe:
            httpGet:
              path: /actuator/health
              port: 8082
            initialDelaySeconds: 30
            periodSeconds: 10
