apiVersion: v1
kind: Secret
metadata:
  name: event-backend-db
type: Opaque
stringData:
  SPRING_DATASOURCE_URL: jdbc:postgresql://51.255.203.187:5432/events
  SPRING_DATASOURCE_USERNAME: mahmoud
  SPRING_DATASOURCE_PASSWORD: mahmoud123
